### ISSUE TITLE
Override configs after loading from file

### ISSUE THREAD

**Issue by ddiu8081** [antfu/unconfig#20]
Suppose I got some configurations from CLI, and I want to merge them with the configurations read from the file.

```bash
$ my-cli dev --force --output custom_path
```

Can I do this with `unconfig`?

Like:
```js
import { loadConfig } from 'unconfig'

const { force, output } = '(cli-options)'
const { config, sources } = await loadConfig({
  sources: [
    // load from `my.config.xx`
    {
      files: 'my.config',
    },
    // ...
  ],
  // override configs after sources
  override: {
    mode: {
      force: force,
    },
    outDir: output,
  },
  merge: false,
})
```

**Comment by stevending1st** [comment]
You may need `cwd`, a configuration item that is not specified in the documentation.

https://github.com/antfu/unconfig/blob/c0b45c736dd6a6a58f03d5f41cc6fd75fc3bf16b/src/types.ts#L45-L50

use case:

https://github.com/unocss/unocss/blob/ee117d7c83e5708daaf9f3408b6edebd0c3436f3/packages/config/src/index.ts#L37-L56

I don't know if the following code will work, as you expected.

```ts
import { loadConfig } from 'unconfig'

const { force, output } = '(cli-options)'
const { config, sources } = await loadConfig({
  sources: [
    // load from `my.config.xx`
    {
      files: 'my.config',
    },
    // ...
  ],
  // override configs after sources
  override: {
    mode: {
      force: force,
    },
    outDir: output,
  },
  merge: false,
  cwd: output
})
```

**Comment by antfu** [comment]
If you would need `overrides` instead of `defaults`, you can always do it afterward with the `config` object, isn't it? If so I feel it might not worth for the complexity here.

**Comment by ddiu8081** [comment]
Yes, I now also think it might be more appropriate to do this logic externally. Thanks for the suggestion!
