### ISSUE TITLE
compare with c12/rc9?

### ISSUE THREAD

**Issue by husayt** [antfu/unconfig#30]
### Clear and concise description of the problem

Wanted to understand author's vision for this library and how it compares to [rc9](https://unjs.io/packages/rc9)/[c12](https://unjs.io/packages/c12). All three libraries are related so it will be useful to understand the scope for each of them

### Suggested solution

This is just a question, but hopefully will be good to include the answer in the readme. 

### Additional context

Thank you for great effort

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Just use c12 I would say. `unconfig` was a try to be able to load plugin configs fields from framework configs like `vite.config.js` `nuxt.config.js`, but in the end it didn't work well and it would be still more efficient and reliable to have a dedicated config file.
